### ISSUE TITLE
Linux compilation

### ISSUE THREAD

**Issue by rasikhq** [Roughsketch/libdiscord#6]
Hello, I've been using this library very successfully and happily, on windows that is, I'd like a little help in getting this to compile on linux since when I follow the instructions on readme it throws exceptions on g++

Thanks!

![image](https://user-images.githubusercontent.com/16344370/51827374-0c54b080-230b-11e9-949f-77ceafe4160f.png)

**Comment by Roughsketch** [comment]
This issue is the same as #3, but that was closed since the person never responded.

Basically the issue as far as I'm aware is the guild method in the channel class conflicts with the actual guild class name. I imagine changing the guild method name in the channel class to something like `get_guild` or similar would fix it.

**Comment by rasikhq** [comment]
There is a name conflict I guess, indeed, but what you suggested did not help, it seems like the class guild declaration in connection_object.h causes this issue, I'm trying to but unable to understand and pave a way to a fix

**Comment by Roughsketch** [comment]
I fixed two errors in the linux build with https://github.com/Roughsketch/libdiscord/commit/aa3d27201a2a7d0fa8e54c112675112173f5300a

However, the last error is something that I don't know if it's easy to fix. Basically the `m_guilds` member in connection_state has an incomplete type for guild since it's just forward declared and unordered_map doesn't work with incomplete types. I changed the type to a normal map instead, but I run into other issues later on.

I can try to look at this later and push any updates to the linux-fix branch.

**Comment by Roughsketch** [comment]
It seems there are just multiple instances of name conflicts on linux. Windows doesn't seem to care if `class user` conflicts with a method like `guild::user`, but Linux does. 

One fix for this is to go back to my very original version of this library where class names were capitalized. So instead of `class guild`, you'd get `class Guild`, and similar for User, Channel, Member, etc. I like this better than making every method `get_*`.

Any thoughts?

**Comment by rasikhq** [comment]
A capitalized one is indeed better than the other one, in terms of readability and explanation, really appreciating the fact that you're helping, cheers mate!

**Comment by Roughsketch** [comment]
I made the changes (https://github.com/Roughsketch/libdiscord/commit/abac644ccf3fe0645e892118cbb6f1c058ffea95), and it now compiles in Ubuntu. I haven't tested it in windows.

Let me know if this change works for you.

**Comment by rasikhq** [comment]
Awesome! Now it compiles, however there was a small issue for Windows build which was simply fixed by 'changing' the variable name. For Debian the lib/libdiscord.so wasn't working so I changed LIB=lib/libdiscord.so to LIB=libdiscord.so in my case for it to work.

I can make a pull request with the linux-fix and the name fix for Visual studio if you desire otherwise you can change the name according to how it suits you.

Line 67: Changed "Embed Embed = Embed()" to "Embed embed = Embed()"

**Comment by Roughsketch** [comment]
I added the fix. There were a few places where the same issue came up.

If all is working on Linux and Windows with the current branch, I'll merge it into master.

**Comment by rasikhq** [comment]
Rest is fine, but you forgot this one:

channel_api.cpp: 135

` if (!embed.empty())
        {
          writer.String("embed");
          embed.Serialize(writer);
        }`

Changed "Embed" to "embed" fixes it on Windows. (Linux as well)
