### ISSUE TITLE
attempting to reference a deleted function

### ISSUE THREAD

**Issue by NotDark** [Roughsketch/libdiscord#7]
![image](https://user-images.githubusercontent.com/44568476/53476526-8bc1d500-3aad-11e9-8453-ddfc2fa9561b.png)

**Comment by NotDark** [comment]
@Roughsketch  any fix?

**Comment by Roughsketch** [comment]
I tagged need more info because I can't tell what may be causing your issue with only part of the code. I know at least one other person is using this library successfully, so I don't know if this is a windows specific error or something you have misconfigured.

I should also mention I do not have the dev environment setup to compile or check the library, and since this is unmaintained I do not plan on setting it up. If I can't get a sense after you provide more information, it will be up to you.

**Comment by Roughsketch** [comment]
Closing due to lack of update.

**Comment by maxsupermanhd** [comment]
So trying to make examples work. (cloned git repo inside)
`main.cpp:11:32: error: use of deleted function ‘discord::Bot::Bot(const discord::Bot&)’`
Full compile log: [here](https://pastebin.com/QU9bPNf3)
Makefile: [here](https://pastebin.com/J6qK7R2G)
Library built successfully and .so object in `libdiscord/lib` seems valid. (but it fails at the compile step)

**Comment by maxsupermanhd** [comment]
P.S. Compiling with command from README outputs same error.
